<?php

namespace AppBundle\Repository;

/**
 * AprendizajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AprendizajeRepository extends \Doctrine\ORM\EntityRepository
{
}
