<?php

namespace AppBundle\Repository;

/**
 * ConductaIndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConductaIndicadorRepository extends \Doctrine\ORM\EntityRepository
{
}
