<?php

namespace AppBundle\Repository;

/**
 * ConocimientoAprendizajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConocimientoAprendizajeRepository extends \Doctrine\ORM\EntityRepository
{
}
