<?php

namespace AppBundle\Repository;

/**
 * ConocimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConocimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
