<?php

namespace AppBundle\Repository;

/**
 * EvaluacionPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionPersonaRepository extends \Doctrine\ORM\EntityRepository
{
}
