<?php

namespace AppBundle\Repository;

/**
 * EvaluacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluacionRepository extends \Doctrine\ORM\EntityRepository
{
}
