<?php

namespace AppBundle\Repository;

/**
 * PerfilConductaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilConductaRepository extends \Doctrine\ORM\EntityRepository
{
}
