<?php

namespace AppBundle\Repository;

/**
 * PerfilConocimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilConocimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
